/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BoostIndexRouteImport } from './routes/boost.index'
import { Route as BoostAdRouteImport } from './routes/boost.ad'
import { Route as BoostAudienceRouteImport } from './routes/boost.audience'
import { Route as BoostBudgetRouteImport } from './routes/boost.budget'
import { Route as BoostLinkRouteImport } from './routes/boost.link'
import { Route as BoostPayRouteImport } from './routes/boost.pay'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as MetaCallbackRouteImport } from './routes/meta.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostIndexRoute = BoostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoostRoute,
} as any)
const BoostAdRoute = BoostAdRouteImport.update({
  id: '/ad',
  path: '/ad',
  getParentRoute: () => BoostRoute,
} as any)
const BoostAudienceRoute = BoostAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => BoostRoute,
} as any)
const BoostBudgetRoute = BoostBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => BoostRoute,
} as any)
const BoostLinkRoute = BoostLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => BoostRoute,
} as any)
const BoostPayRoute = BoostPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => BoostRoute,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaCallbackRoute = MetaCallbackRouteImport.update({
  id: '/meta/callback',
  path: '/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boost': typeof BoostRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/boost/ad': typeof BoostAdRoute
  '/boost/audience': typeof BoostAudienceRoute
  '/boost/budget': typeof BoostBudgetRoute
  '/boost/link': typeof BoostLinkRoute
  '/boost/pay': typeof BoostPayRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/meta/callback': typeof MetaCallbackRoute
  '/boost/': typeof BoostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/boost/ad': typeof BoostAdRoute
  '/boost/audience': typeof BoostAudienceRoute
  '/boost/budget': typeof BoostBudgetRoute
  '/boost/link': typeof BoostLinkRoute
  '/boost/pay': typeof BoostPayRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/meta/callback': typeof MetaCallbackRoute
  '/boost': typeof BoostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boost': typeof BoostRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/boost/ad': typeof BoostAdRoute
  '/boost/audience': typeof BoostAudienceRoute
  '/boost/budget': typeof BoostBudgetRoute
  '/boost/link': typeof BoostLinkRoute
  '/boost/pay': typeof BoostPayRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/meta/callback': typeof MetaCallbackRoute
  '/boost/': typeof BoostIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boost'
    | '/inbox'
    | '/login'
    | '/studio'
    | '/boost/ad'
    | '/boost/audience'
    | '/boost/budget'
    | '/boost/link'
    | '/boost/pay'
    | '/campaigns/$id'
    | '/meta/callback'
    | '/boost/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/login'
    | '/studio'
    | '/boost/ad'
    | '/boost/audience'
    | '/boost/budget'
    | '/boost/link'
    | '/boost/pay'
    | '/campaigns/$id'
    | '/meta/callback'
    | '/boost'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/boost'
    | '/inbox'
    | '/login'
    | '/studio'
    | '/boost/ad'
    | '/boost/audience'
    | '/boost/budget'
    | '/boost/link'
    | '/boost/pay'
    | '/campaigns/$id'
    | '/meta/callback'
    | '/boost/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoostRoute: typeof BoostRouteWithChildren
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  MetaCallbackRoute: typeof MetaCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost/': {
      id: '/boost/'
      path: '/'
      fullPath: '/boost/'
      preLoaderRoute: typeof BoostIndexRouteImport
      parentRoute: typeof BoostRoute
    }
    '/boost/ad': {
      id: '/boost/ad'
      path: '/ad'
      fullPath: '/boost/ad'
      preLoaderRoute: typeof BoostAdRouteImport
      parentRoute: typeof BoostRoute
    }
    '/boost/audience': {
      id: '/boost/audience'
      path: '/audience'
      fullPath: '/boost/audience'
      preLoaderRoute: typeof BoostAudienceRouteImport
      parentRoute: typeof BoostRoute
    }
    '/boost/budget': {
      id: '/boost/budget'
      path: '/budget'
      fullPath: '/boost/budget'
      preLoaderRoute: typeof BoostBudgetRouteImport
      parentRoute: typeof BoostRoute
    }
    '/boost/link': {
      id: '/boost/link'
      path: '/link'
      fullPath: '/boost/link'
      preLoaderRoute: typeof BoostLinkRouteImport
      parentRoute: typeof BoostRoute
    }
    '/boost/pay': {
      id: '/boost/pay'
      path: '/pay'
      fullPath: '/boost/pay'
      preLoaderRoute: typeof BoostPayRouteImport
      parentRoute: typeof BoostRoute
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/callback': {
      id: '/meta/callback'
      path: '/meta/callback'
      fullPath: '/meta/callback'
      preLoaderRoute: typeof MetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoostRouteChildren {
  BoostAdRoute: typeof BoostAdRoute
  BoostAudienceRoute: typeof BoostAudienceRoute
  BoostBudgetRoute: typeof BoostBudgetRoute
  BoostLinkRoute: typeof BoostLinkRoute
  BoostPayRoute: typeof BoostPayRoute
  BoostIndexRoute: typeof BoostIndexRoute
}

const BoostRouteChildren: BoostRouteChildren = {
  BoostAdRoute: BoostAdRoute,
  BoostAudienceRoute: BoostAudienceRoute,
  BoostBudgetRoute: BoostBudgetRoute,
  BoostLinkRoute: BoostLinkRoute,
  BoostPayRoute: BoostPayRoute,
  BoostIndexRoute: BoostIndexRoute,
}

const BoostRouteWithChildren = BoostRoute._addFileChildren(BoostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoostRoute: BoostRouteWithChildren,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  MetaCallbackRoute: MetaCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
